---
title: "Assignment 1: Introduction"
author: "Masha Edmondson"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Salk_A03_Introduction.Rmd") prior to submission.

The completed exercise is due on Tuesday, January 14th at 1:00 pm.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have experience using MatLAB and python with my undergraduate thesis. I worked with R software class in my junior year of college; however it was 4 years ago and the R software looks completely different from today. I have done some informal training with panolpy course provided by Duke.

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident in my ability to understand code, and look for small nuiances that might have caused an error. I feel confident in my ability to learn code.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am apprehensive about trouble shooting code, and computer glitches out of anyone's control because it seems to me that technology is not always kind to me. I am also slightly apprehensive about getting behind in class due to errors and spending class time catching up instead of learning.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/m12edmon/Environmental_Data_Analytics_2020


