\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={Assignment 3: Data Exploration},
            pdfauthor={Masha Edmondson},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=2.54cm]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{Assignment 3: Data Exploration}
\author{Masha Edmondson}
\date{}

\begin{document}
\maketitle

\hypertarget{overview}{%
\subsection{OVERVIEW}\label{overview}}

This exercise accompanies the lessons in Environmental Data Analytics on
Data Exploration.

\hypertarget{directions}{%
\subsection{Directions}\label{directions}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Change ``Student Name'' on line 3 (above) with your name.
\item
  Work through the steps, \textbf{creating code and output} that fulfill
  each instruction.
\item
  Be sure to \textbf{answer the questions} in this assignment document.
\item
  When you have completed the assignment, \textbf{Knit} the text and
  code into a single PDF file.
\item
  After Knitting, submit the completed exercise (PDF file) to the
  dropbox in Sakai. Add your last name into the file name (e.g.,
  ``Salk\_A03\_DataExploration.Rmd'') prior to submission.
\end{enumerate}

The completed exercise is due on Tuesday, January 28 at 1:00 pm.

\hypertarget{set-up-your-r-session}{%
\subsection{Set up your R session}\label{set-up-your-r-session}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Check your working directory, load necessary packages (tidyverse), and
  upload two datasets: the ECOTOX neonicotinoid dataset
  (ECOTOX\_Neonicotinoids\_Insects\_raw.csv) and the Niwot Ridge NEON
  dataset for litter and woody debris
  (NEON\_NIWO\_Litter\_massdata\_2018-08\_raw.csv). Name these datasets
  ``Neonics'' and ``Litter'', respectively.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Set up your working directory}
\KeywordTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "/Users/mashaedmondson/Desktop/Environmental_Data_Analytics_2020/Assignments"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Load packges}
\KeywordTok{library}\NormalTok{(tidyverse)}

\CommentTok{#Import datasets}
\NormalTok{Neonics.data <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"../Data/Raw/ECOTOX_Neonicotinoids_Insects_raw.csv"}\NormalTok{)}
\NormalTok{Litter.data <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"../Data/Raw/NEON_NIWO_Litter_massdata_2018-08_raw.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{learn-about-your-system}{%
\subsection{Learn about your system}\label{learn-about-your-system}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  The neonicotinoid dataset was collected from the Environmental
  Protection Agency's ECOTOX Knowledgebase, a database for ecotoxicology
  research. Neonicotinoids are a class of insecticides used widely in
  agriculture. The dataset that has been pulled includes all studies
  published on insects. Why might we be interested in the ecotoxicologoy
  of neonicotinoids on insects? Feel free to do a brief internet search
  if you feel you need more background information.
\end{enumerate}

\begin{quote}
Answer: Neonicotinoid is a common inseciticide used in agirculture that
resembles nicotine. There has been research that shows neonicotinoid
insecticide is linked to declining bee populations. Therefore, it is
important to know what types of insects are located in agricultural
areas that use this inseciticide. There have not been an abundance of
long term studies on the impacts of neonicotinoids on local insect
populations, which is important to know. Some insects provide necessary
pollination of crops, which could be adversly affected by the
inseciticide. It would also be helpful to know what insects are in the
areas, and if there are any drastic declines in the populations that
could be linked to the use of Neonicotinoids.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  The Niwot Ridge litter and woody debris dataset was collected from the
  National Ecological Observatory Network, which collectively includes
  81 aquatic and terrestrial sites across 20 ecoclimatic domains. 32 of
  these sites sample forest litter and woody debris, and we will focus
  on the Niwot Ridge long-term ecological research (LTER) station in
  Colorado. Why might we be interested in studying litter and woody
  debris that falls to the ground in forests? Feel free to do a brief
  internet search if you feel you need more background information.
\end{enumerate}

\begin{quote}
Answer: Litter is an important factor in ecosystem dynamics, as it is
indicative of ecological productivity and may be useful in predicting
regional nutrient cycling and soil fertility. This detritus organic
material and its constituent nutrients can be absorbed into the top
layer of soil. The amount of litter can also inform us about the primary
production of forests. It could also indicates areas that could be more
susceptible to fires. Litterfall and fine woody debris data may be used
to esimate annual Aboveground Net Primary Productivity (ANPP) and
aboveground biomass at plot, site, and conƟnental scales. They also
provide essential data for understanding vegetative carbon fluxes over
time.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  How is litter and woody debris sampled as part of the NEON network?
  Read the NEON\_Litterfall\_UserGuide.pdf document to learn more. List
  three pieces of salient information about the sampling methods here:
\end{enumerate}

\begin{quote}
Answer: Litter is defined as material that is dropped from the forest
canopy and has a butt end diameter \textless{}2cm and a length
\textless{}50 cm. This material is collected in elevated 0.5m2 PVC
traps. Fine woody debris is defined as material that is dropped from the
forest canopy and has a butt end diameter \textless{}2cm and a length
\textgreater{}50 cm. This material is collected in ground traps or
elevated PVC litter traps. Litter and fine woody debris sampling is
executed at terrestrial NEON sites that contain woody vegetaƟon
\textgreater{}2m tall. The litter sampling is targeted to take place in
40m x 40m plots that range in amounts from 4-20 samples. One litter trap
pair is deployed for every 400 m2 plot area. Trap placement within plots
may be either targeted or randomized, depending on the vegetation. The
NEON network has specific protocols that must be adhered to in order to
correctly sample litter fall given different areas and climates. Three
pieces of salient information about the sampling methods are: * Defining
litter to be a material that is dropped from the forest canopy and has a
butt end diameter \textless{}2cm and a length \textless{}50 cm. * Larger
rectangular ground traps may be more appropriate to collect litterfall
samples that are specifically 3 m x 0.5 m rectangular area. *Litter and
fine woody debris sampling is executed at terrestrial NEON sites that
contain woody vegetation \textgreater{}2m tall.
\end{quote}

\hypertarget{obtain-basic-summaries-of-your-data-neonics}{%
\subsection{Obtain basic summaries of your data
(Neonics)}\label{obtain-basic-summaries-of-your-data-neonics}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  What are the dimensions of the dataset?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(Neonics.data) }\CommentTok{# rows: 4623 columns: 30}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4623   30
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Using the \texttt{summary} function, determine the most common effects
  that are studied. Why might these effects specifically be of interest?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(Neonics.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    CAS.Number       
##  Min.   : 58842209  
##  1st Qu.:138261413  
##  Median :138261413  
##  Mean   :147651982  
##  3rd Qu.:153719234  
##  Max.   :210880925  
##                     
##                                                                                 Chemical.Name 
##  (2E)-1-[(6-Chloro-3-pyridinyl)methyl]-N-nitro-2-imidazolidinimine                     :2658  
##  3-[(2-Chloro-5-thiazolyl)methyl]tetrahydro-5-methyl-N-nitro-4H-1,3,5-oxadiazin-4-imine: 686  
##  [C(E)]-N-[(2-Chloro-5-thiazolyl)methyl]-N'-methyl-N''-nitroguanidine                  : 452  
##  (1E)-N-[(6-Chloro-3-pyridinyl)methyl]-N'-cyano-N-methylethanimidamide                 : 420  
##  N''-Methyl-N-nitro-N'-[(tetrahydro-3-furanyl)methyl]guanidine                         : 218  
##  [N(Z)]-N-[3-[(6-Chloro-3-pyridinyl)methyl]-2-thiazolidinylidene]cyanamide             : 128  
##  (Other)                                                                               :  61  
##                                                    Chemical.Grade
##  Not reported                                             :3989  
##  Technical grade, technical product, technical formulation: 422  
##  Pestanal grade                                           :  93  
##  Not coded                                                :  53  
##  Commercial grade                                         :  27  
##  Analytical grade                                         :  15  
##  (Other)                                                  :  24  
##                                                  Chemical.Analysis.Method
##  Measured                                                    : 230       
##  Not coded                                                   :  51       
##  Not reported                                                :   5       
##  Unmeasured                                                  :4321       
##  Unmeasured values (some measured values reported in article):  16       
##                                                                          
##                                                                          
##  Chemical.Purity                  Species.Scientific.Name
##  NR     :2502    Apis mellifera               : 667      
##  25     : 244    Bombus terrestris            : 183      
##  50     : 200    Apis mellifera ssp. carnica  : 152      
##  20     : 189    Bombus impatiens             : 140      
##  70     : 112    Apis mellifera ssp. ligustica: 113      
##  75     :  89    Popillia japonica            :  94      
##  (Other):1287    (Other)                      :3274      
##             Species.Common.Name
##  Honey Bee            : 667    
##  Parasitic Wasp       : 285    
##  Buff Tailed Bumblebee: 183    
##  Carniolan Honey Bee  : 152    
##  Bumble Bee           : 140    
##  Italian Honeybee     : 113    
##  (Other)              :3083    
##                                                        Species.Group 
##  Insects/Spiders                                              :3569  
##  Insects/Spiders; Standard Test Species                       :  27  
##  Insects/Spiders; Standard Test Species; U.S. Invasive Species: 667  
##  Insects/Spiders; U.S. Invasive Species                       : 360  
##                                                                      
##                                                                      
##                                                                      
##     Organism.Lifestage  Organism.Age             Organism.Age.Units
##  Not reported:2271     NR     :3851   Not reported        :3515    
##  Adult       :1222     2      : 111   Day(s)              : 327    
##  Larva       : 437     3      : 105   Instar              : 255    
##  Multiple    : 285     <24    :  81   Hour(s)             : 241    
##  Egg         : 128     4      :  81   Hours post-emergence:  99    
##  Pupa        :  69     1      :  59   Year(s)             :  64    
##  (Other)     : 211     (Other): 335   (Other)             : 122    
##                     Exposure.Type         Media.Type  
##  Environmental, unspecified:1599   No substrate:2934  
##  Food                      :1124   Not reported: 663  
##  Spray                     : 393   Natural soil: 393  
##  Topical, general          : 254   Litter      : 264  
##  Ground granular           : 249   Filter paper: 230  
##  Hand spray                : 210   Not coded   :  51  
##  (Other)                   : 794   (Other)     :  88  
##               Test.Location  Number.of.Doses        Conc.1.Type..Author.
##  Field artificial    :  96   2      :2441    Active ingredient:3161     
##  Field natural       :1663   3      : 499    Formulation      :1420     
##  Field undeterminable:   4   5      : 314    Not coded        :  42     
##  Lab                 :2860   6      : 230                               
##                              4      : 221                               
##                              NR     : 217                               
##                              (Other): 701                               
##  Conc.1..Author. Conc.1.Units..Author.              Effect    
##  0.37/  : 208    AI kg/ha  : 575       Population      :1803  
##  10/    : 127    AI mg/L   : 298       Mortality       :1493  
##  NR/    : 108    AI lb/acre: 277       Behavior        : 360  
##  NR     :  94    AI g/ha   : 241       Feeding behavior: 255  
##  1      :  82    ng/org    : 231       Reproduction    : 197  
##  1023   :  80    ppm       : 180       Development     : 136  
##  (Other):3924    (Other)   :2821       (Other)         : 379  
##               Effect.Measurement    Endpoint                   Response.Site 
##  Abundance             :1699     NOEL   :1816   Not reported          :4349  
##  Mortality             :1294     LOEL   :1664   Midgut or midgut gland:  63  
##  Survival              : 133     LC50   : 327   Not coded             :  51  
##  Progeny counts/numbers: 120     LD50   : 274   Whole organism        :  41  
##  Food consumption      : 103     NR     : 167   Hypopharyngeal gland  :  27  
##  Emergence             :  98     NR-LETH:  86   Head                  :  23  
##  (Other)               :1176     (Other): 289   (Other)               :  69  
##  Observed.Duration..Days.       Observed.Duration.Units..Days.
##  1      : 713             Day(s)               :4394          
##  2      : 383             Emergence            :  70          
##  NR     : 355             Growing season       :  48          
##  7      : 207             Day(s) post-hatch    :  20          
##  3      : 183             Day(s) post-emergence:  17          
##  0.0417 : 133             Tiller stage         :  15          
##  (Other):2649             (Other)              :  59          
##                                                                            Author    
##  Peck,D.C.                                                                    : 208  
##  Frank,S.D.                                                                   : 100  
##  El Hassani,A.K., M. Dacher, V. Gary, M. Lambin, M. Gauthier, and C. Armengaud:  96  
##  Williamson,S.M., S.J. Willis, and G.A. Wright                                :  93  
##  Laurino,D., A. Manino, A. Patetta, and M. Porporato                          :  88  
##  Scholer,J., and V. Krischik                                                  :  82  
##  (Other)                                                                      :3956  
##  Reference.Number
##  Min.   :   344  
##  1st Qu.:108459  
##  Median :165559  
##  Mean   :142189  
##  3rd Qu.:168998  
##  Max.   :180410  
##                  
##                                                                                                                                         Title     
##  Long-Term Effects of Imidacloprid on the Abundance of Surface- and Soil-Active Nontarget Fauna in Turf                                    : 200  
##  Reduced Risk Insecticides to Control Scale Insects and Protect Natural Enemies in the Production and Maintenance of Urban Landscape Plants: 100  
##  Effects of Sublethal Doses of Acetamiprid and Thiamethoxam on the Behavior of the Honeybee (Apis mellifera)                               :  96  
##  Exposure to Neonicotinoids Influences the Motor Function of Adult Worker Honeybees                                                        :  93  
##  Toxicity of Neonicotinoid Insecticides on Different Honey Bee Genotypes                                                                   :  88  
##  Chronic Exposure of Imidacloprid and Clothianidin Reduce Queen Survival, Foraging, and Nectar Storing in Colonies of Bombus impatiens     :  82  
##  (Other)                                                                                                                                   :3964  
##                                            Source     Publication.Year
##  Agric. For. Entomol.11(4): 405-419           : 200   Min.   :1982    
##  Environ. Entomol.41(2): 377-386              : 100   1st Qu.:2005    
##  Arch. Environ. Contam. Toxicol.54(4): 653-661:  96   Median :2010    
##  Ecotoxicology23:1409-1418                    :  93   Mean   :2008    
##  Bull. Insectol.66(1): 119-126                :  88   3rd Qu.:2013    
##  PLoS One9(3): 14 p.                          :  82   Max.   :2019    
##  (Other)                                      :3964                   
##  Summary.of.Additional.Parameters                                                                                                                                                                                                                       
##  Purity: \xca NR - NR | Organism Age: \xca NR - NR Not reported | Conc 1 (Author): \xca Active ingredient NR/ - NR/ AI kg/ha | Duration (Days): \xca NR - NR NR | Conc 2 (Author): \xca NR (NR - NR) NR | Conc 3 (Author): \xca NR (NR - NR) NR  : 389  
##  Purity: \xca NR - NR | Organism Age: \xca NR - NR Not reported | Conc 1 (Author): \xca Active ingredient NR - NR AI lb/acre | Duration (Days): \xca NR - NR NR | Conc 2 (Author): \xca NR (NR - NR) NR | Conc 3 (Author): \xca NR (NR - NR) NR  : 138  
##  Purity: \xca NR - NR | Organism Age: \xca NR - NR Not reported | Conc 1 (Author): \xca Active ingredient NR - NR AI kg/ha | Duration (Days): \xca NR - NR NR | Conc 2 (Author): \xca NR (NR - NR) NR | Conc 3 (Author): \xca NR (NR - NR) NR    : 136  
##  Purity: \xca NR - NR | Organism Age: \xca NR - NR Not reported | Conc 1 (Author): \xca Active ingredient NR/ - NR/ AI lb/acre | Duration (Days): \xca NR - NR NR | Conc 2 (Author): \xca NR (NR - NR) NR | Conc 3 (Author): \xca NR (NR - NR) NR: 124  
##  Purity: \xca NR - NR | Organism Age: \xca NR - NR Not reported | Conc 1 (Author): \xca Active ingredient NR - NR AI ng/org | Duration (Days): \xca NR - NR NR | Conc 2 (Author): \xca NR (NR - NR) NR | Conc 3 (Author): \xca NR (NR - NR) NR   :  94  
##  Purity: \xca NR - NR | Organism Age: \xca NR - NR Not reported | Conc 1 (Author): \xca Formulation NR - NR ml/ha | Duration (Days): \xca NR - NR NR | Conc 2 (Author): \xca NR (NR - NR) NR | Conc 3 (Author): \xca NR (NR - NR) NR             :  80  
##  (Other)                                                                                                                                                                                                                                         :3662
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(Neonics.data}\OperatorTok{$}\NormalTok{Effect)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Accumulation        Avoidance         Behavior     Biochemistry 
##               12              102              360               11 
##          Cell(s)      Development        Enzyme(s) Feeding behavior 
##                9              136               62              255 
##         Genetics           Growth        Histology       Hormone(s) 
##               82               38                5                1 
##    Immunological     Intoxication       Morphology        Mortality 
##               16               12               22             1493 
##       Physiology       Population     Reproduction 
##                7             1803              197
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(Neonics.data}\OperatorTok{$}\NormalTok{Effect.Measurement)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                           Abundance 
##                                                1699 
##                                           Mortality 
##                                                1294 
##                                            Survival 
##                                                 133 
##                              Progeny counts/numbers 
##                                                 120 
##                                    Food consumption 
##                                                 103 
##                                           Emergence 
##                                                  98 
##                      Search/explore/forage behavior 
##                                                  96 
##                           Feeding behavior, general 
##                                                  92 
##                                  Chemical avoidance 
##                                                  65 
##                                              Weight 
##                                                  48 
##           Distance moved, change in direct movement 
##                                                  38 
##                                    Feeding behavior 
##                                                  36 
##                                     Flying behavior 
##                                                  30 
##               Accuracy of learned task, performance 
##                                                  28 
##                                           Sex ratio 
##                                                  27 
##                                           Fecundity 
##                                                  26 
##                                  Stimulus avoidance 
##                                                  26 
##                                   Righting response 
##                                                  24 
##                                            Lifespan 
##                                                  23 
##                                       Acquired task 
##                                                  22 
##                                               Hatch 
##                                                  21 
##                                  Predatory behavior 
##                                                  21 
##                                Acetylcholinesterase 
##                                                  20 
##                                                Walk 
##                                                  19 
##                                   Freezing behavior 
##                                                  18 
##                      Reproductive success (general) 
##                                                  17 
##        Slowed, Retarded, Delayed or Non-development 
##                                                  17 
##                                            Grooming 
##                                                  16 
##                                            Diameter 
##                                                  14 
##                                             Residue 
##                                                  12 
##                                   Activity, general 
##                                                  11 
##                                      Food avoidance 
##                                                  11 
##                                             Control 
##                                                   9 
##                      Developmental changes, general 
##                                                   9 
##                          Intrinsic rate of increase 
##                                                   9 
##                                    Pollen collected 
##                                                   9 
##                                                Size 
##                                                   9 
##                                            Esterase 
##                                                   8 
##                               Intoxication, general 
##                                                   8 
##                         Mortality/survival, general 
##                                                   8 
##      Population change (change in N/change in time) 
##                                                   8 
##                                         Smell/Sniff 
##                                                   8 
##                                             Biomass 
##                                                   7 
##                                       Catalase mRNA 
##                                                   7 
##                                     Generation time 
##                                                   7 
##                                            Infected 
##                                                   7 
##                                         Orientation 
##                                                   7 
##                            Population doubling time 
##                                                   7 
##                              Population growth rate 
##                                                   7 
##                                        Sealed brood 
##                                                   7 
##                                   Vitellogenin mRNA 
##                                                   7 
##                                        Ali esterase 
##                                                   6 
## Apoptosis, programmed cell death, DNA fragmentation 
##                                                   6 
##                                    Carboxylesterase 
##                                                   6 
##                                            Hemocyte 
##                                                   6 
##                                           Knockdown 
##                                                   6 
##                                           Viability 
##                                                   6 
##                                          Extinction 
##                                                   5 
##                               Net Reproductive Rate 
##                                                   5 
##                                  Polyphenol oxidase 
##                                                   5 
##                                    Prey penetration 
##                                                   5 
##                                            Pupation 
##                                                   5 
##                               Reproducing organisms 
##                                                   5 
##   Amount or percent animals infested with parasites 
##                                                   4 
##              Continual reinforcement task performed 
##                                                   4 
##                                     Defensin 1 mRNA 
##                                                   4 
##                                 Diversity, Evenness 
##                                                   4 
##              Encapsulation or Melanization Response 
##                                                   4 
##                          General biochemical effect 
##                                                   4 
##                           Glutathione S-transferase 
##                                                   4 
##                       Histological changes, general 
##                                                   4 
##                                     Life expectancy 
##                                                   4 
##                         Thioredoxin peroxidase mRNA 
##                                                   4 
##                      Vanin-like protein 1-like mRNA 
##                                                   4 
##                                   Bees wax produced 
##                                                   3 
##                         Behavioral changes, general 
##                                                   3 
##                                            Catalase 
##                                                   3 
##                                       Cell turnover 
##                                                   3 
##                                    Cytochrome P-450 
##                                                   3 
##                                        Feeding time 
##                                                   3 
##                                              Length 
##                                                   3 
##                                      Protein, total 
##                                                   3 
##                                         Respiration 
##                                                   3 
##                         Response time to a stimulus 
##                                                   3 
##                                               Stage 
##                                                   3 
##                               Time to first progeny 
##                                                   3 
##                                      Trehalase mRNA 
##                                                   3 
##                                Alkaline phosphatase 
##                                                   2 
##             Carboxylesterase clade I, member 1 mRNA 
##                                                   2 
##                                     Centractin mRNA 
##                                                   2 
##                                    Chitinase 5 mRNA 
##                                                   2 
##                           Colony maintenance (bees) 
##                                                   2 
##                                           COX2 mRNA 
##                                                   2 
##                               Endoplasmin-like mRNA 
##                                                   2 
##                                   Gamete production 
##                                                   2 
##                        Glucose dehydrogenase 2 mRNA 
##                                                   2 
##                       Glucosinolate sulphatase mRNA 
##                                                   2 
##                  Glutathione peroxidase-like 1 mRNA 
##                                                   2 
##                  Glutathione peroxidase-like 2 mRNA 
##                                                   2 
##                                             (Other) 
##                                                  77
\end{verbatim}

\begin{quote}
Answer: The most common effects that are studied in this dataset are
abundance and mortality. The summary reveals 1699 abundance and 1294
mortality recorded. In a study that is researching the impacts of the
incesticide on insects, it is important to know abundance estimations
and also noted mortalities. This could help determine what effect
Neonicotinoids have on insect populations.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Using the \texttt{summary} function, determine the six most commonly
  studied species in the dataset (common name). What do these species
  have in common, and why might they be of interest over other insects?
  Feel free to do a brief internet search for more information if
  needed.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(Neonics.data}\OperatorTok{$}\NormalTok{Species.Common.Name)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                          Honey Bee                     Parasitic Wasp 
##                                667                                285 
##              Buff Tailed Bumblebee                Carniolan Honey Bee 
##                                183                                152 
##                         Bumble Bee                   Italian Honeybee 
##                                140                                113 
##                    Japanese Beetle                  Asian Lady Beetle 
##                                 94                                 76 
##                     Euonymus Scale                           Wireworm 
##                                 75                                 69 
##                  European Dark Bee                  Minute Pirate Bug 
##                                 66                                 62 
##               Asian Citrus Psyllid                      Parastic Wasp 
##                                 60                                 58 
##             Colorado Potato Beetle                    Parasitoid Wasp 
##                                 57                                 51 
##                Erythrina Gall Wasp                       Beetle Order 
##                                 49                                 47 
##        Snout Beetle Family, Weevil           Sevenspotted Lady Beetle 
##                                 47                                 46 
##                     True Bug Order              Buff-tailed Bumblebee 
##                                 45                                 39 
##                       Aphid Family                     Cabbage Looper 
##                                 38                                 38 
##               Sweetpotato Whitefly                      Braconid Wasp 
##                                 37                                 33 
##                       Cotton Aphid                     Predatory Mite 
##                                 33                                 33 
##             Ladybird Beetle Family                         Parasitoid 
##                                 30                                 30 
##                      Scarab Beetle                      Spring Tiphia 
##                                 29                                 29 
##                        Thrip Order               Ground Beetle Family 
##                                 29                                 27 
##                 Rove Beetle Family                      Tobacco Aphid 
##                                 27                                 27 
##                       Chalcid Wasp             Convergent Lady Beetle 
##                                 25                                 25 
##                      Stingless Bee                  Spider/Mite Class 
##                                 25                                 24 
##                Tobacco Flea Beetle                   Citrus Leafminer 
##                                 24                                 23 
##                    Ladybird Beetle                          Mason Bee 
##                                 23                                 22 
##                           Mosquito                      Argentine Ant 
##                                 22                                 21 
##                             Beetle         Flatheaded Appletree Borer 
##                                 21                                 20 
##               Horned Oak Gall Wasp                 Leaf Beetle Family 
##                                 20                                 20 
##                  Potato Leafhopper         Tooth-necked Fungus Beetle 
##                                 20                                 20 
##                       Codling Moth          Black-spotted Lady Beetle 
##                                 19                                 18 
##                       Calico Scale                Fairyfly Parasitoid 
##                                 18                                 18 
##                        Lady Beetle             Minute Parasitic Wasps 
##                                 18                                 18 
##                          Mirid Bug                   Mulberry Pyralid 
##                                 18                                 18 
##                           Silkworm                     Vedalia Beetle 
##                                 18                                 18 
##              Araneoid Spider Order                          Bee Order 
##                                 17                                 17 
##                     Egg Parasitoid                       Insect Class 
##                                 17                                 17 
##           Moth And Butterfly Order       Oystershell Scale Parasitoid 
##                                 17                                 17 
## Hemlock Woolly Adelgid Lady Beetle              Hemlock Wooly Adelgid 
##                                 16                                 16 
##                               Mite                        Onion Thrip 
##                                 16                                 16 
##              Western Flower Thrips                       Corn Earworm 
##                                 15                                 14 
##                  Green Peach Aphid                          House Fly 
##                                 14                                 14 
##                          Ox Beetle                 Red Scale Parasite 
##                                 14                                 14 
##                 Spined Soldier Bug              Armoured Scale Family 
##                                 14                                 13 
##                   Diamondback Moth                      Eulophid Wasp 
##                                 13                                 13 
##                  Monarch Butterfly                      Predatory Bug 
##                                 13                                 13 
##              Yellow Fever Mosquito                Braconid Parasitoid 
##                                 13                                 12 
##                       Common Thrip       Eastern Subterranean Termite 
##                                 12                                 12 
##                             Jassid                         Mite Order 
##                                 12                                 12 
##                          Pea Aphid                   Pond Wolf Spider 
##                                 12                                 12 
##           Spotless Ladybird Beetle             Glasshouse Potato Wasp 
##                                 11                                 10 
##                           Lacewing            Southern House Mosquito 
##                                 10                                 10 
##            Two Spotted Lady Beetle                         Ant Family 
##                                 10                                  9 
##                       Apple Maggot                            (Other) 
##                                  9                                670
\end{verbatim}

\begin{quote}
Answer: The six most commonly studied insects are Honey Bees (667
reports), Parasitic Wasp (285 reports), Buff Tailed Bumblebees (183
reports), the Carniolan Honey Bee (152 reports), Bumble bee (140
reports), and the Italian Honeybee (113 reports). These species are all
types of bees and pollinators that play an important role in every
aspect of the ecosystem. They support the growth of trees, flowers, and
other plants, which serve as food and shelter for other organisms. Bees
contribute to complex, interconnected ecosystems that allow a diverse
number of different species to co-exist. The are responsible for
pollianting and distrubting plants that aids biodiveristy and
productivity. Parasitic wasps are increasingly used in agricultural pest
control as they themselves do little or no damage to crops. Farmers buy
these parasitic wasps for insect control in their fields. Not only are
parasitic wasps important for pest control, but they are also necessary
as pollinators in agriculture and home gardens.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Concentrations are always a numeric value. What is the class of
  Conc.1..Author. in the dataset, and why is it not numeric?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{class}\NormalTok{(Neonics.data}\OperatorTok{$}\NormalTok{Conc.}\DecValTok{1}\NormalTok{..Author.)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "factor"
\end{verbatim}

\begin{quote}
Answer:The class of Conc.1..Author is a factor. It is not numeric
classification because it is missing some numerical values in the
columns or the numerica data appears to be incomplete.
\end{quote}

\hypertarget{explore-your-data-graphically-neonics}{%
\subsection{Explore your data graphically
(Neonics)}\label{explore-your-data-graphically-neonics}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  Using \texttt{geom\_freqpoly}, generate a plot of the number of
  studies conducted by publication year.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Neonics.data)}\OperatorTok{+}
\KeywordTok{geom_freqpoly}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Publication.Year))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{A03_DataExploration_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\tightlist
\item
  Reproduce the same graph but now add a color aesthetic so that
  different Test.Location are displayed as different colors.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Neonics.data)}\OperatorTok{+}
\KeywordTok{geom_freqpoly}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Publication.Year, }\DataTypeTok{color=}\NormalTok{Test.Location))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{A03_DataExploration_files/figure-latex/unnamed-chunk-7-1.pdf}

Interpret this graph. What are the most common test locations, and do
they differ over time?

\begin{quote}
Answer: The lab appears to be the most common test location starting
around early 2000s until the present. ``Field natural'' test location
was more common beginning early 1990s, but have fluctuated since 2000s.
The ``artifical field'' test locations were rarely used throughout the
whole time spand from 1980-2020.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{10}
\tightlist
\item
  Create a bar graph of Endpoint counts. What are the two most common
  end points, and how are they defined? Consult the ECOTOX\_CodeAppendix
  for more information.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Neonics.data, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Endpoint)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{A03_DataExploration_files/figure-latex/unnamed-chunk-8-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(Neonics.data}\OperatorTok{$}\NormalTok{Endpoint)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    EC10    EC50    IC50    LC10    LC20    LC25    LC30    LC50    LC75    LC90 
##       6      11       6      15       5       1       6     327       1      37 
##    LC95    LC99    LD05    LD30    LD50    LD90    LD95    LOEC    LOEL    LT25 
##      36       2       1       1     274       6       7      17    1664       1 
##    LT50    LT90    LT99    NOEC    NOEL      NR NR-LETH NR-ZERO 
##      65       7       2      19    1816     167      86      37
\end{verbatim}

\begin{quote}
Answer: The two most common end points are NOEL and LOEL. NOEL is
defined by their count, or the number of times they appeared in the
dataset. NOEL had a count of 1816, and LOEL had a count of 1664.
\end{quote}

\hypertarget{explore-your-data-litter}{%
\subsection{Explore your data (Litter)}\label{explore-your-data-litter}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\tightlist
\item
  Determine the class of collectDate. Is it a date? If not, change to a
  date and confirm the new class of the variable. Using the
  \texttt{unique} function, determine which dates litter was sampled in
  August 2018.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{class}\NormalTok{(Litter.data}\OperatorTok{$}\NormalTok{collectDate) }\CommentTok{#factor}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "factor"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Litter.data}\OperatorTok{$}\NormalTok{collectDate <-}\StringTok{ }\KeywordTok{as.Date}\NormalTok{(Litter.data}\OperatorTok{$}\NormalTok{collectDate, }\DataTypeTok{format =} \StringTok{"%Y-%m-%d"}\NormalTok{) }
\KeywordTok{class}\NormalTok{(Litter.data}\OperatorTok{$}\NormalTok{collectDate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Date"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Litter was collected August 2nd and August 30th in 2018}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{12}
\tightlist
\item
  Using the \texttt{unique} function, determine how many plots were
  sampled at Niwot Ridge. How is the information obtained from
  \texttt{unique} different from that obtained from \texttt{summary}?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{unique}\NormalTok{(Litter.data}\OperatorTok{$}\NormalTok{plotID)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] NIWO_061 NIWO_064 NIWO_067 NIWO_040 NIWO_041 NIWO_063 NIWO_047 NIWO_051
##  [9] NIWO_058 NIWO_046 NIWO_062 NIWO_057
## 12 Levels: NIWO_040 NIWO_041 NIWO_046 NIWO_047 NIWO_051 NIWO_057 ... NIWO_067
\end{verbatim}

\begin{quote}
Answer: 12 different plots were sampled at Niwot Ridge. The information
obtained from the ``unique'' function eliminates duplicate elements/rows
from a vector, data frame or array. The summary function produces a
summary of all records in the found in the dataset which can include
duplicates.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{13}
\tightlist
\item
  Create a bar graph of functionalGroup counts. This shows you what type
  of litter is collected at the Niwot Ridge sites. Notice that litter
  types are fairly equally distributed across the Niwot Ridge sites.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Litter.data, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ functionalGroup)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{A03_DataExploration_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(Litter.data}\OperatorTok{$}\NormalTok{functionalGroup)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        Flowers         Leaves          Mixed        Needles          Other 
##             23             24             10             30             24 
##          Seeds Twigs/branches Woody material 
##             23             28             26
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{14}
\tightlist
\item
  Using \texttt{geom\_boxplot} and \texttt{geom\_violin}, create a
  boxplot and a violin plot of dryMass by functionalGroup.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Litter.data) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ functionalGroup, }\DataTypeTok{y =}\NormalTok{ dryMass)) }\CommentTok{#box plot}
\end{Highlighting}
\end{Shaded}

\includegraphics{A03_DataExploration_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Litter.data) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_violin}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ functionalGroup, }\DataTypeTok{y =}\NormalTok{ dryMass)) }\CommentTok{#violin plot}
\end{Highlighting}
\end{Shaded}

\includegraphics{A03_DataExploration_files/figure-latex/unnamed-chunk-12-2.pdf}

Why is the boxplot a more effective visualization option than the violin
plot in this case?

\begin{quote}
Answer: The boxplot is a more effective visualization option than the
violin plot becuase it better visualizes the data provided. It
illustrates the the interquartile range, median, variabilities, and
statistical outliers clearly. It also provides some indication of the
data's symmetry and skewness. The violin plot, which displays density
distributions, illustrated very little for the data provided. It could
not clearly show information about sample counts, medians, interquartile
ranges, and lower/upper values. It makes the data appear incomplete.
\end{quote}

What type(s) of litter tend to have the highest biomass at these sites?

\begin{quote}
Answer: Needles and woody material litter tend to have the highest
biomass at these sites.
\end{quote}

\end{document}
